### ISSUE TITLE
No data showing. No host selectable

### ISSUE THREAD

**Issue by skinfrakkijm** [rfmoz/grafana-dashboards#108]
No host on drop down. No data in the metrics. Tested on Prometheus with a query. Data is coming back fine. Tested query in Grafana. Data comes back fine

![image](https://user-images.githubusercontent.com/21244400/198737202-a2fda76c-ed3a-410c-b4ba-0532cad1145b.png)

**Comment by HubertGL** [comment]
Did you import via ID or json? Because when I imported with ID I got all blank. Now with json import only the http status codes are missing
