### ISSUE TITLE
[feat] CPU Frequency

### ISSUE THREAD

**Issue by Cronus89** [rfmoz/grafana-dashboards#111]
It would be nice to monitor fluctuations in CPU Frequency in MHz

**Comment by AustinLeath** [comment]
does prometheus export CPU frequency?

**Comment by Cronus89** [comment]
Yes the node_exporter has min max, and the current

**Comment by towolf** [comment]
I've created a PR for this in #122

**Comment by AustinLeath** [comment]
looks like this can be closed

**Comment by towolf** [comment]
Yeah, my PR wasn't merged at all, only closed?
