### ISSUE TITLE
Grafana button plugins

### ISSUE THREAD

**Issue by Shadrack88** [rfmoz/grafana-dashboards#112]
my plan is not  display texts in grafana, but to use a button plugins and variable entering options that will allow the end-user to enter a value, press the button i created, and send the value to a device. as shown in the image below 
in the the image below, i enter the value 60 and pressed the button to send the paylaod via HTTP integration

i used the POST HTTP method, but its appears as OPTIONS on the receiver side
[grafana button.pdf](https://github.com/rfmoz/grafana-dashboards/files/10238069/grafana.button.pdf)

**Comment by rfmoz** [comment]
You can customize the dashboard to fit your use case after fork it. Thanks
