### ISSUE TITLE
Some charts are Blank and show "No Data" message

### ISSUE THREAD

**Issue by obounaim** [rfmoz/grafana-dashboards#117]
Hi,

I am currently tring to scrape EKS/(AWS K8S managed service) nodes metrics. You can find bellow the versions used.

Some graphs are working good (like "Memory Basic" and "Memory Stack"), however other graphs are not. 
The graphs bellow are empty and show "No data" message.

* CPU Basic
* Network Traffic Basic
* CPU Network Traffic
* Disk IOps
* ..... Same issue with other graphs

|node-exporter-full|r29|
|Grafana|v9.3.6|
|Prometheus-Node-Exporter|4.13.0|
|Prometheus-Sever|19.3.1|
|EKS|1.24|

**Comment by rfmoz** [comment]
As anybody reported the same issue along this time, it seems related with your particular Grafana / Prometheus setup.
