### ISSUE TITLE
Host selector showing only 1 host

### ISSUE THREAD

**Issue by marceloaba** [rfmoz/grafana-dashboards#118]
I have multiple hosts under the same job "node" but the dashboard only shows 1 host to select. When I open Prometheus target I can see that there are two endpoints as expected but the second one is not available in the host selector dropdown.
![Screen Shot 2023-02-01 at 11 37 13 AM](https://user-images.githubusercontent.com/45857579/216105287-2cd29422-8614-4ade-b39e-60be77b2061a.png)

**Comment by mantis4** [comment]
Same. Сould you fix it?

**Comment by rfmoz** [comment]
I don't see this issue on any of the available dashboards. It seems an issue with this particular Grafana / Prometheus setup.
