### ISSUE TITLE
How to configure HAProxy to collect data from remote host

### ISSUE THREAD

**Issue by mentax007** [rfmoz/grafana-dashboards#127]
Hi. i'm new with promitheus and grafana. 
Could somebody explain where I need to configure port/url to be able to collect data from haproxy server?

**Comment by gqdc** [comment]
Hello,
from the HAProxy documentation : https://www.haproxy.com/blog/haproxy-exposes-a-prometheus-metrics-endpoint#configuring-haproxy

Add this frontend : 

```
frontend stats
   bind *:8404
   option http-use-htx
   http-request use-service prometheus-exporter if { path /metrics }
   stats enable
   stats uri /stats
   stats refresh 10s
```

Restart HAProxy, and voilà
