### ISSUE TITLE
Doesn't show CPU graph under FreeBSD

### ISSUE THREAD

**Issue by iron-udjin** [rfmoz/grafana-dashboards#128]
OS: FreeBSD 13-STABLE
prometheus: 2.41.0
grafana: 9.4.7
node_exporter: 1.5.0

![Screenshot](https://user-images.githubusercontent.com/1779285/231578630-9beabcd4-5fea-4ea0-91c9-f3bf6c3cee97.png)

Is there way to fix it?

**Comment by woorszt** [comment]
Run into the same issue. Any progress on this one?

**Comment by woorszt** [comment]
Thx for your quick response. Got it working again.

Had to change "Standard Option -> Min: 0" to "auto (empty)"

**Comment by rfmoz** [comment]
Fixed on #138

Thanks,
