### ISSUE TITLE
ConfigMap `metadata.annotations` too long

### ISSUE THREAD

**Issue by zalegrala** [rfmoz/grafana-dashboards#136]
When applying the most recent version of the dashboard, I get the following error.
```
The ConfigMap "dashboards-nodesfull-0" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

Is anyone else also seeing this issue?

**Comment by aufkm** [comment]
same

**Comment by rfmoz** [comment]
As pointed in the [Kubernetes doc](https://kubernetes.io/docs/concepts/configuration/configmap/):

`A ConfigMap is not designed to hold large chunks of data. The data stored in a ConfigMap cannot exceed 1 MiB. If you need to store settings that are larger than this limit, you may want to consider mounting a volume or use a separate database or file service.`
