### ISSUE TITLE
No CPU and Network data in Firefox

### ISSUE THREAD

**Issue by mihaigalos** [rfmoz/grafana-dashboards#137]
Hi,

Seems Firefox doesn't display CPU Basic and Network Traffic Basic data:
<img width="1723" alt="Bildschirmfoto 2023-06-08 um 18 41 07" src="https://github.com/rfmoz/grafana-dashboards/assets/16443090/5a7cd55e-0c30-4f61-a764-2075242f89ba">

Interesingly, CPU Busy works. Also, I do get data displayed in Chrome:
<img width="1712" alt="Bildschirmfoto 2023-06-08 um 18 53 55" src="https://github.com/rfmoz/grafana-dashboards/assets/16443090/c60d7548-1e9c-4424-b3f2-05aeda8fa8ff">

This however only works with 24h resolution, if I select anything else, it's the same `No data` as in Firefox.
 
Versions of tools used:
* Dashboard node-exporter-full_rev31 from [here](https://grafana.com/grafana/dashboards/1860-node-exporter-full/)
* Raspberry Pi, 4GB, Ubuntu 23.04, k3s version v1.27.1+k3s1
* Grafana version 9.5.2
* Prometheus version 2.44.0 (branch: HEAD, revision: 1ac5131f698ebc60f13fe2727f89b115a41f6558)
* Node Exporter, version 1.5.0 (branch: HEAD, revision: 1b48970ffcf5630534fb00bb0687d73c66d1c959)
* Firefox version 114.0 (arm64 on Mac M1)
* Chrome version 113.0.5672.126 (arm64 on Mac M1)

**Comment by Alone2** [comment]
I do have the same Issue, only that I can't replicate the display of the data selecting 24h with a different browser.  However, I can see the data if I select 7 days. 

I do have the same Issue with the following versions:
- Grafana: v10.0.1 (5a30620b85)
- Prometheus: v2.40.5
- prometheus-node-exporter: 0.17.0 (Debian 10), 1.3.1 (Rocky Linux 8)
- Node exporter Full dashboard: Version on grafana.com/grafana/dashboards from 2023-03-30T13:35:21
- Browsers tested: Google Chrome 114.0.5735.199 (Windows 11), Chromium 114.0.5735.198 (Arch Linux), Firefox 114.0.2 (Arch Linux) and Microsoft Edge 98.0.1100.3 (Arch Linux)

**Comment by Alone2** [comment]
I was able to fix the issue by setting the 'Scrape interval' in 'Home > Administration > Data sources > Prometheus' to the value defined in Prometheus (in my case 5m):
```
  - job_name: systems
    scrape_interval: 5m
    metrics_path: '/system'
    static_configs:
      - targets: ['MYHOSTNAME:PORT']
```
I found this answer in the following pull request: #120

**Comment by lyz-code** [comment]
If you have set the datasource as a json, you need to tweak the `timeInterval` field. For example:

```json
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      timeInterval: 30s
      prometheusType: Prometheus
      prometheusVersion: 2.42.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      exemplarTraceIdDestinations: []

```
