### ISSUE TITLE
No data available when interval is less than 24 hours

### ISSUE THREAD

**Issue by Pinkolik** [rfmoz/grafana-dashboards#140]
![image](https://github.com/rfmoz/grafana-dashboards/assets/26690061/b035a8a9-2208-4970-a718-c449982f75d9)
Hello!
Whenever I'm trying to view metrics in an interval smaller than 24 hours, all CPU dashboards show only 'No data available' message. However, when interval equals 24 hours or greater everything works fine.
Any suggestions?

Thank you in advance!

**Comment by mpostument** [comment]
Have the same issue

**Comment by mpostument** [comment]
That helped. Thank you
