### ISSUE TITLE
No data showing

### ISSUE THREAD

**Issue by cat007mine** [rfmoz/grafana-dashboards#143]
Hi all.

All my panels are showing N/A.
At the top where I select datasource (Prometheus), there is nothing to select in Job or Host, other than 'None'.

My prometheus.yml has:

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # Example job for node_exporter
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node_exporter:9100']

  # Example job for cadvisor
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
- job_name: node
    static_configs:
      - targets: ['localhost:9100']

Any ideas?

**Comment by supermarin** [comment]
confirming this is  the case on master. if you zoom out to 24h , data shows up. will test with older commits

**Comment by supermarin** [comment]
Fixed, in my case Prometheus was using the default scrape_interval of 1m. Changing this to 15s in global config made it working

**Comment by rfc1036** [comment]
I think that this happens to enough people that it would be a good idea to add a note to the documentation.

**Comment by davordbetter** [comment]
Same problem here.
Default scrape interval is 1m

But changing scrape interval to 15s is not best idea in my case.
Tried to change Min interval in Query options to 1m but still no data. After changing to 2m it works. 

But this does not end up same as scrape interval.
Is there any other solution?

**Comment by mweinelt** [comment]
Configure the `scrape_interval` forr the datasource as described in the READMe and it will work.

**Comment by jzielke84** [comment]
I'm getting some metric data but no cpu data. And the part of the ReadMe about `timeInterval` is confusing. There is no such option in the datasource gui for that. The board was working fine until I updated it.
