### ISSUE TITLE
Layout Error

### ISSUE THREAD

**Issue by sagebase** [rfmoz/grafana-dashboards#155]
![ảnh](https://github.com/rfmoz/grafana-dashboards/assets/111110592/e9d110b8-0759-4dd8-9c65-b2128c4a62dd)

Error layout, please check!

**Comment by Pinockel** [comment]
Grafana Version v10.2.2 - Working
Grafana Version v10.2.3 - Layout error

Grafana downgrade fixed the problem

**Comment by eminjk** [comment]
Temp fix: manually edit each gauge and change Gauge/ Orientation (Layout orientation) to `Auto`

**Comment by skl256** [comment]
Me too.
grafana-oss:10.2.2 - ok
grafana-oss:10.2.3 - same problem
![image](https://github.com/rfmoz/grafana-dashboards/assets/111241000/6efee47a-6fe5-49db-baff-9f4df2b74c53)
Chrome 120.0.6099.217 @ Windows 11
