### ISSUE TITLE
Bytes in/out are multiplied by 8

### ISSUE THREAD

**Issue by ChristopherZellermann** [rfmoz/grafana-dashboards#162]
Hello,

In the haproxy-full.json and haproxy-2-full.json files, for all metrics related to "haproxy_*_bytes_in_*" or "haproxy_*_bytes_out_*, the values are multiplied by 8.
Since the values provided by the HAProxy metrics page are already bytes and not bits, the *8 seems wrong.

Or maybe I am missing something ?

Christopher

**Comment by rfmoz** [comment]
Hello,

Please, take a look to #37 It's a similar case.

Thanks,
