### ISSUE TITLE
[haproxy-2] Frontend cache uses $backend variable

### ISSUE THREAD

**Issue by matejzero** [rfmoz/grafana-dashboards#164]
In Cache / compressor section, all graphs for frontend metrics is using wrong label `proxy=~$backend` instead of `proxy=~$frontend`, so you get no data.

Examples: 
- https://github.com/rfmoz/grafana-dashboards/blob/master/prometheus/haproxy-2-full.json#L6159
- https://github.com/rfmoz/grafana-dashboards/blob/master/prometheus/haproxy-2-full.json#L6172

I tried changing it to `$frontend` and it's working as intended.

**Comment by rfmoz** [comment]
Thanks for report the issue.
