### ISSUE TITLE
Convert panels from 'graph' to 'timeseries' plugin

### ISSUE THREAD

**Issue by crutonjohn** [rfmoz/grafana-dashboards#167]
Grafana has deprecated and is planning to remove the old `graph` angular panel plugin: https://grafana.com/docs/grafana/latest/developers/angular_deprecation

most, if not all, could be updated by using a find/replace or a simple `sed`. tested this on the NFS dashboard and things worked fine, but i'm not sure what other dashboards may be affected.

**Comment by PikachuEXE** [comment]
How to make graph like `CPU Basic` to have percentage again?
Simply replacing `graph` with `timeseries` won't work
![image](https://github.com/rfmoz/grafana-dashboards/assets/1018543/b24143b3-d87d-483d-9725-8ae842cb2fea)

**Comment by crutonjohn** [comment]
ah maybe it's gonna take a bit more work than i had thought then.

**Comment by rfmoz** [comment]
When edit a graph, the dashboard have a button to migrate. All done.

Thanks for the deprecation notice.
