### ISSUE TITLE
No data on dashboard on Node Exporter Full

### ISSUE THREAD

**Issue by rafaborges83** [rfmoz/grafana-dashboards#177]
After a brand new install of Grafana and Prometheus, I imported the 1860 (Node Exporter Full) dashboard

Some of the dashboard is loading fine, but others like CPU Basic, CPU Busy, Pressure and all network graphs are showing No Data and the following error message:

bad_data: 1:94: parse error: bad duration syntax: "1m0".

The grafana server version is 11.3.0 (commit: d9455ff7db73b694db7d412e49a68bec767f2b5a, branch: HEAD), installed on Red Hat Enterprise Linux release 8.10.

Prometheus version is 2.16.0

Thanks
![Screenshot_3](https://github.com/user-attachments/assets/ccd65db8-bbb3-440d-afaa-70c03f0b0f31)
![Screenshot_1](https://github.com/user-attachments/assets/25f316ce-2135-49e2-8da6-371be54ed8de)

**Comment by bashtian-fr** [comment]
Same thing here, even tried older version, it only show some data when I use 24h or 48h time range

**Comment by bashtian-fr** [comment]
I think it is also being discussed here https://github.com/rfmoz/grafana-dashboards/issues/169

**Comment by rafaborges83** [comment]
Hi Bashtian, I managed to fix this.

The problem is with the variable $__rate_interval. PromQL was not able to understand it.

So, I replaced that value to 5m and it started showing the graphs.

Hope this helps you.

Thanks
