### ISSUE TITLE
Encounter negative values of CPU Busy during upgrade/downtime of platform 

### ISSUE THREAD

**Issue by ChengYanJin** [rfmoz/grafana-dashboards#73]
Hello, 

In our use case, we imported the [`node-exporter-full`](https://github.com/rfrail3/grafana-dashboards/raw/bda97a0407517ae3afcf573e56605ca891848fcd/prometheus/node-exporter-full.json) dashboard to monitor our platform. 

As shown in the screenshot, we got negative values during the upgrade/downtime.
![image](https://user-images.githubusercontent.com/18453133/107075523-823d5d80-67ea-11eb-81c5-287e8953ffc7.png)
so we are considering switching to another expression to avoid the unexpected negative values.
```
100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle",instance=~"${instanceIP}:${PORT_NODE_EXPORTER}"}[5m])) * 100)
```
![image](https://user-images.githubusercontent.com/18453133/107074713-65ecf100-67e9-11eb-867f-9b2581a31cf3.png)

Would do you consider it's an issue or a bug on your side? 
And how would you suggest to solve the issue?

Thanks in advance!

**Comment by rfmoz** [comment]
Please, update to the latest dashboard version, it have improvements over cpu calculation.
